springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: "routepick-api"
      paths-to-match: "/api/**"
      packages-to-scan: com.routepick.api
