spring:
  profiles:
    active: dev
  application:
    name: routepick-admin

# 공통 로깅 설정
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO

# 공통 서버 설정
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
